# Generated by Codex on 2026-02-18
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_userquota"),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMConfiguration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("openrouter_api_key", models.CharField(blank=True, max_length=255)),
                (
                    "openrouter_model",
                    models.CharField(default="qwen/qwen3-next-80b-a3b-instruct:free", max_length=255),
                ),
                ("openrouter_timeout", models.PositiveIntegerField(default=45)),
                ("openrouter_max_retries", models.PositiveIntegerField(default=1)),
                ("openrouter_temperature", models.FloatField(default=0.2)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
