# Generated by Codex on 2026-02-18
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_llmconfiguration"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmconfiguration",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="llmconfiguration",
            name="name",
            field=models.CharField(default="Default", max_length=100),
        ),
    ]
