# Generated by Codex on 2026-02-18
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_llmconfiguration_crud"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmconfiguration",
            name="openrouter_backup_models",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Daftar model backup, pisahkan dengan baris baru atau koma.",
            ),
        ),
    ]
