# Generated by Codex on 2026-02-18
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_llmconfiguration_backup_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemSetting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("registration_enabled", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
