# Generated by Django 6.0.1 on 2026-02-19 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_userloginpresence'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userloginpresence',
            new_name='core_userlo_is_acti_22952d_idx',
            old_name='core_userlo_is_acti_1f1838_idx',
        ),
        migrations.RenameIndex(
            model_name='userloginpresence',
            new_name='core_userlo_user_id_736c7c_idx',
            old_name='core_userlo_user_id_6cad17_idx',
        ),
    ]
