"""
Django settings for config project.
Generated by 'django-admin startproject' using Django 6.0.1.
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-default-key-change-me')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = ['localhost', '127.0.0.1']


# ==========================================
# 1. APPLICATION DEFINITION
# ==========================================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # --- LIBRARY PIHAK KETIGA ---
    'rest_framework', # Opsional
    'inertia',        # WAJIB: Penghubung Django <-> React
    'django_vite',    # WAJIB: Manajemen Aset Frontend
    
    # --- APP ANDA ---
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    # WAJIB: Middleware Inertia (Taruh setelah Auth & Message)
    'inertia.middleware.InertiaMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            # ❌ HAPUS BAGIAN 'libraries' YANG KITA BUAT TADI
            # Biarkan kosong atau hapus baris 'libraries' {...} sepenuhnya
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# ==========================================
# 2. DATABASE & PASSWORD
# ==========================================
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

AUTH_PASSWORD_VALIDATORS = [
    { 'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator', },
]


# ==========================================
# 3. INTERNATIONALIZATION
# ==========================================
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Jakarta' # WIB
USE_I18N = True
USE_TZ = True


# ==========================================
# 4. STATIC FILES & VITE CONFIGURATION
# ==========================================
STATIC_URL = '/static/'

# 1. TAMBAHKAN INI (WAJIB ADA)
# Ini adalah folder tempat Django mengumpulkan semua file statis saat mau deploy.
# Meskipun di localhost belum dipakai deployment, django-vite tetap mengeceknya.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# 2. Pastikan ini tetap ada
STATICFILES_DIRS = [
    BASE_DIR / 'core' / 'static',
]

# Konfigurasi Django-Vite
DJANGO_VITE_ASSETS_PATH = BASE_DIR / 'core' / 'static' / 'dist'
DJANGO_VITE_DEV_MODE = DEBUG
DJANGO_VITE_DEV_SERVER_PORT = 5173


# ==========================================
# 5. INERTIA CONFIGURATION
# ==========================================
# Nama file HTML utama yang akan memuat React (ada di core/templates/base.html)
INERTIA_LAYOUT = 'base.html'


# ==========================================
# 6. MEDIA FILES (UPLOAD)
# ==========================================
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ==========================================
# 7. AUTHENTICATION REDIRECTS
# ==========================================
LOGIN_URL = 'login' 
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'login'


# ==========================================
# 8. LOGGING (MONITORING DETAIL)
# ==========================================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'colored': {
            '()': 'colorlog.ColoredFormatter',
            # Menampilkan: [Waktu] Level [NamaFile:Baris] Pesan
            'format': '%(log_color)s[%(asctime)s] %(levelname)-8s [%(filename)s:%(lineno)d] %(message)s',
            'datefmt': '%H:%M:%S',
            'log_colors': {
                'DEBUG':    'cyan',
                'INFO':     'green',
                'WARNING':  'yellow',
                'ERROR':    'red',
                'CRITICAL': 'red,bg_white',
            },
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'colored',
        },
    },
    'loggers': {
        'core': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'django.server': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        # Opsional: Log Inertia kalau ada error komunikasi
        'inertia': {
            'handlers': ['console'],
            'level': 'WARNING',
        },
    },
}